# Generated by Django 2.1.2 on 2018-10-20 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_delivery_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Waiting for courier to pick-up'), (2, 'Courier is on the way'), (3, 'Package has been delivered')], default=1),
        ),
    ]
