version: '3'

services:
  db:
    image: postgres:10.5-alpine
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - .env

  app: &app
    image: hack_mercari_app
    build:
      context: .
      dockerfile: ./docker/backend/local/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./docs:/docs
      - ./shared/media:/app/shared/media
      - ./shared/static:/app/shared/static
      - ./shared/templates:/app/shared/templates

  web:
    image: hack_mercari_web
    build:
      context: .
      dockerfile: ./docker/frontend/local/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
